### ISSUE TITLE
How would I inject dependencies into controllers (or anything else)?

### ISSUE THREAD

**Issue by nackjicholson** [hanami/hanami-router#20]
Is there a technique I'm unaware of for injecting dependencies into the controllers. Or with `lotus/lotus` I might want to inject dependencies into view classes as well, can't figure out how I would go about that either.

I was looking through `endpoint_resolver.rb` and it occurred to me that with the way it makes instances of the action class, I don't have a clear way to inject dependencies into them. Maybe you know a way? Please tell me.

Let's say I have an action, and I want it to be set with an instance of the redcarpet markdown parser and not have to make an instance of it in line. (Because injecting dependencies makes things easier to test and more loosely coupled).

``` ruby
require 'redcarpet'

module Blog
  module Controllers
    module Posts
      class Show
        include Lotus::Action
        expose :markup

        attr_writer :markdown

        def call(params)
          contents = File.open("posts/#{params[:slug]}.md") { |f| f.read }
          @markup = @markdown.render(contents)
        end
      end
  end
end
```

With that markdown as a settable, easily mocked dependency this class is easier to test and has the added benefit of not being coupled to the HTML renderer, it could have been set with any type. As you can see the action below only renders HTML, but the one above doesn't have that constraint.

``` ruby
def call(params)
  markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML);
  contents = File.open("posts/#{params[:slug]}.md") { |f| f.read }
  @markup = markdown.render(contents)
end
```

**Comment by chrismcleod** [comment]
Something like this worked for me (dont like re-opening classes though):

```
module Lotus
  module Routing
    class ClassEndpoint
      def call(env)
        dependencies = __getobj__.instance_method(:initialize).parameters.collect { |p| p[1] if [:keyreq, :key].include?(p[0]) }
        instances = {}
        dependencies.each do |dependency|
          instances[dependency] = Common::Application::DependencyRegistry.instance(dependency)
        end
        __getobj__.new(**instances).call(env)
      end
    end
  end
end
```
